export { default as FinalsListScreen } from './finals/list.tsx';
export { default as HomeScreen } from './home';
export { default as TakePictureStepScreen } from './image_recognition/takePictureStep';
export { default as LandingScreen } from './landing';
export { default as PreRegisterScreen } from './preregister';
export { default as PreRegisterLastInstructionsScreen } from './preregister/done';
export { default as SplashScreen } from './splash';
// export FinalDateTimePickerScreen from './finals/finalDateTimePicker.tsx';
// export QRGeneratorScreen from './qr_generator';
// export FinalExamsListScreen from './finalExams';
